import {
  // Baby,
  // BookOpen,
  // BriefcaseBusiness,
  Building2,
  Car,
  Dumbbell,
  // Factory,
  HeartPulse,
  Home,
  Laptop,
  Package,
  // PawPrint,
  Shirt,
  Smartphone,
  Sofa,
  // ToyBrick,
  // Tractor,
  // Wrench,
  LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  vehicles: Car,
  "real-estate": Building2,
  "mobile-tablet": Smartphone,
  "digital-goods": Laptop,
  "home-kitchen": Home,
  "home-appliances": Sofa,
  "fashion-clothing": Shirt,
  "beauty-health": HeartPulse,
  "sport-travel": Dumbbell,
  // books: BookOpen,
  // toys: ToyBrick,
  // baby: Baby,
  // pets: PawPrint,
  // industry: Factory,
  // agriculture: Tractor,
  // services: Wrench,
  // jobs: BriefcaseBusiness,

  default: Package,
};
